### ISSUE TITLE
Record with multiple fields reverts to first field

### ISSUE THREAD

**Issue by Staticfarm** [thtliife/servicenow-sync#3]
A local file that is syncing with serviceNow that has more that one field (eg. UI Page: HTML; Client Script; Processing Script) reverts to the first field (e.g. HTML from Client Script) when the SN-Sync configuration window is closed. Sync (manual or on save) doesn't occur.

**Comment by thtliife** [comment]
Please test and let me know how u go.

**Comment by Staticfarm** [comment]
Resolved in version 0.2.12. Many thanks.
